version: '3.4'

services:
  da-verifier:
    image: mantlenetworkio/l2geth:v0.4.0-1
    entrypoint: sh ./geth.sh
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ./goerli/envs/daverifier.env
    volumes:
      - ./data/verifier:/root/.ethereum/geth/
    environment:
      ETH1_HTTP: ${RPC_URL} #goerli
      SEQUENCER_L1_RPC: ${RPC_URL} #goerli
      SEQUENCER_CLIENT_HTTP: https://rpc.testnet.mantle.xyz
      ROLLUP_STATE_DUMP_PATH:  https://mantlenetworkio.github.io/networks/goerli/genesis.json
      ROLLUP_CLIENT_HTTP: https://dtl.testnet.mantle.xyz
      BLOCK_SIGNER_KEY: ${key} #22c7fa2d2cf5c0ccc21ff32a210d7dfea7bbc7d16c3ba0a75302a7b51c16c4f7 
      BLOCK_SIGNER_ADDRESS: '' # 0xa9eC80835800a59Fd022f53e3E75AA4552F22ccB  
    ports:
      - "3545:8545"
      - "3546:8546"
      - "33303:30303"
  tss-node:
    image: mantlenetworkio/tss:v0.4.0
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - da-verifier
    volumes:
      - ./.tssnode:/data
      - ./config:/app/config
    environment:
      TSS_NODE_PRIVATE_KEY: ${key}
      TSS_NODE_BOOTSTRAP_PEERS: >
        /ip4/18.143.253.149/tcp/80/p2p/16Uiu2HAmDQ1nNmJCWBaXace81MbxjeixUT1T6UR4qStVn29QY4rc
      TSS_NODE_EXTERNAL_IP: ${PUBLIC IP}
      TSS_SCC_CONTRACT_ADDRESS: 0x654e6dF111F98374d9e5d908D7a5392C308aA18D #CanonicalTransactionChain in goerli/addresses.json
      TSS_TSS_GROUP_CONTRACT_ADDRESS: 0x1938F9551E7482F4bA21dE8cD84c99F94f8A8116 #Proxy__TSS_GroupManager in goerli/addresses.json
      TSS_TSS_STAKING_SLASH_CONTRACT_ADDRESS: 0xF7f039b80108f7985167959e36932fBF86F4ceFE #Proxy__TSS_StakingSlashing in goerli/addresses.json
      TSS_L1_START_BLOCK_NUMBER: 1
      TSS_MISS_SIGNED_NUMBER: 10
      TSS_NODE_GAS_LIMIT_SCALER: 15
      TSS_L1_URL:  ${RPC_URL} ##goerli
      TSS_NODE_L2_ETH_RPC:  "http://da-verifier:8545"
      TSS_NODE_WS_ADDR:  "tcp://k8s-testnet-mantlets-d48bbd6293-a477ba8f7dbfcdc6.elb.ap-southeast-1.amazonaws.com:8081" #"tcp://${MATNLE-TESTNET-TSSMANAGER}:8081"
    command: ./tss node -c config/tss-node-config.toml
    ports:
      - "8080:8080"
      - "8000:8000"
