version: '3.4'

volumes:
  data-volume:

services:
  init:
    build: ./init
    volumes:
      - data-volume:/app/data

  dl-node:
    image: mantlenetworkio/da-node

    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - data-volume:/data/kzg
    environment:
      DL_NODE_CHAIN_ID: 5
      DL_NODE_CHAIN_RPC: https://rpc.ankr.com/eth_goerli
      DL_NODE_CHALLENGE_ORDER: 200000
      DL_NODE_DB_PATH: /data/da-node
      DL_NODE_DLSM_ADDRESS: #find this value in https://github.com/mantlenetworkio/networks/blob/main/goerli/da-address.json#L8
      DL_NODE_FILE_LOG_LEVEL: trace
      DL_NODE_G1_PATH: /data/kzg/g1.point
      DL_NODE_G2_PATH: /data/kzg/g2.point
      DL_NODE_GRAPH_PROVIDER: http://k8s-testnet-graphnod-1f2586e60d-808caf8ff912d31d.elb.ap-southeast-1.amazonaws.com:8000/subgraphs/name/datalayr #graph service of mantle testnet
      DL_NODE_GRPC_PORT: 32000
      DL_NODE_HOSTNAME: ${publicip_of_da-node}
      DL_NODE_LOG_PATH: /data/logs/da-node
      DL_NODE_SRS_ORDER: 200000
      DL_NODE_PRIVATE_BLS: '#fixme' #need a generate bigint （length at least 10）
      DL_NODE_SRS_TABLE_PATH: /data/kzg/SRSTables
      DL_NODE_STD_LOG_LEVEL: debug
      DL_NODE_TIMEOUT: 3000ms
      DL_NODE_CACHE_PATH: data/kzg/SRSTables
      DL_NODE_VERBOSE: true
      DL_NODE_NUM_WORKERS: 8
      DL_NODE_ENABLE_METRICS: true
      DL_NODE_METRICS_PORT: 7001
      DL_NODE_PRIVATE_KEY: ${danode-privatekey}

    ports:
      - ${DL_NODE_GRPC_PORT:-32000}:32000
    depends_on:
      - init

